language: cpp
compiler:
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcre3 libpcre3-dev gromacs
  - sudo apt-get install -qq swig doxygen
  - sudo apt-get install -qq python-numpy python-scipy python-nose

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/OpenMM . 
  - make 
  - make test 
  - make install
  - ls ~/OpenMM/include
  - export LD_LIBRARY_PATH=~/OpenMM/lib/
  - export OPENMM_LIB_PATH=~/OpenMM/lib/
  - export OPENMM_INCLUDE_PATH=~/OpenMM/include/
  - cd python
  - sudo -E python setup.py install
  - cd tests
  - nosetests -vv
#  - python TestAmberPrmtopFile.py
#  - python TestDesmondDMSFile.py
#  - python TestForceField.py
#  - python TestGromacsTopFile.py
#  - python TestModeller.py
#  - python TestNumpyCompatibility.py
#  - python validateConstraints.py
#  - python validateConstraints.pyc
#  - python validateModeller.py
