language: c

install:
  - source tools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  - export CC="gcc -std=c89"
  - source deactivate
  - conda install --yes conda-build
  - # Build the conda package, testing build before packaging.
  - conda build tools/conda-recipe
  - # Install the conda package locally.
  - source activate $python
  - conda install $HOME/miniconda/conda-bld/linux-64/openmm-dev-*
  - conda list -e
  - # Run the Python tests.
  - pushd .
  - cd wrappers/python/tests
  - nosetests -vv --processes=-1 --process-timeout=200
  - popd

env:
  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: Qz3pEYXXFnNQ/WK+15ad4cdbLJvzgCIZRwKD9fLiS3CDO2ldAQWxzaz8RQOwqbFtZUWu7lQpr+GukNJz5p0w18QEto+BxLYG9aW5mjoc+F2vCjyWFjkwnJ/Z/3uBKTcr5x9Y7HKaPGivaJ4BNACifjt7cCpeVJzV6u2+bBgSoHc=

  matrix:
    - python=2.7  CONDA_PY=27
    #- python=3.3  CONDA_PY=33

after_success:
  - echo "after_success"
  - source tools/ci/after_sucess.sh


