language: cpp
compiler:
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install libpcre3 libpcre3-dev
  - sudo apt-get install swig
  - sudo apt-get install doxygen
  - sudo apt-get install python-numpy
  - sudo apt-get install python-scipy
  
script:
  - cmake . && make && make test && sudo make install
  - export LD_LIBRARY_PATH=/OpenMM/lib/
  - export OPENMM_LIB_PATH=/OpenMM/lib/
  - export OPENMM_INCLUDE_PATH=/OpenMM/include/
  - cd python
  - sudo -E python setup.py install
  - cd tests
  - python TestAmberPrmtopFile.py
  - python TestDesmondDMSFile.py
  - python TestForceField.py
  - python TestGromacsTopFile.py
  - python TestModeller.py
  - python TestNumpyCompatibility.py
  - python validateConstraints.py
  - python validateConstraints.pyc
  - python validateModeller.py
