language: cpp
compiler:
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcre3 libpcre3-dev gromacs
  - sudo apt-get install -qq swig doxygen llvm-3.3
  - sudo apt-get install -qq python-numpy python-scipy python-nose
  - export ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-3.3

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/OpenMM -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-g -fsanitize=address -fno-omit-frame-pointer -O2" .
  - make
  - make test
  - make install
  - sudo make PythonInstall
  - cd python/tests
  - nosetests -vv
