package:
  name: openmm
  version: !!str dev

requirements:
  build:
    - cmake
    - python
    - fftw3f

  run:
    - python
    - fftw3f

about:
  home: https://simtk.org/home/openmm
  license: GPL
