package:
  name: openmm
  version: !!str dev

requirements:
  build:
    - cmake
    - python
    - fftw3f

  run:
    - python
    - fftw3f

test:
  requires:
    - cmake
    - nose

  commands:
    - # Test excluding OpenCL tests
    - ctest -j2 -V -E "[A-Za-z]+OpenCL[A-Za-z]+"
    - nosetests -vv --processes=-1 --process-timeout=200

about:
  home: https://simtk.org/home/openmm
  license: GPL
